#TRACING
pn.interop.tracing.base-url=https://api.qa.tracing.interop.pagopa.it
tracing.success.csv.filepath=src/main/resources/tracing/qa/tracing-ok.csv
tracing.error.csv.filepath=src/main/resources/tracing/qa/tracing-error.csv

authorization.server.token.creation.url=https://auth.qa.interop.pagopa.it/token.oauth2
client.assertion.jwt.audience=auth.qa.interop.pagopa.it/client-assertion
bff.base-url=https://selfcare.qa.interop.pagopa.it/1.0/backend-for-frontend
interop-env=qa

#ARCHIVIAZIONE DOCUMENTALE
s3.unsigned-document-base-path=interop-application-documents-qa-es1/qa/generated-documents-unsigned/
s3.signed-document-base-path=interop-signed-application-documents-qa-es1/interop-qa-documents-signer/:year/:onlyMonth/:onlyDay/
s3.unsigned-event-base-path=interop-domain-events-qa-es1/year=:year/month=:onlyMonth/day=:onlyDay/
s3.signed-event-base-path=interop-signed-domain-events-qa-es1/interop-qa-events-signer/:year/:onlyMonth/:onlyDay/

#INTEROP GLOBAL PROPERTIES
remote-wellknown-url=https://qa.interop.pagopa.it/.well-known/jwks.json