#INTEROP GLOBAL PROPERTIES
bff.base-url=https://selfcare.dev.interop.pagopa.it/0.0/backend-for-frontend
m2m.base-url=https://api.dev.interop.pagopa.it/v2
m2m.v3.base-url=https://api.dev.interop.pagopa.it/v3
m2m.v3.agid.jwt.jwks-url=https://api.dev.interop.pagopa.it/.well-known/jwks.json
probing.base-url=https://dev.stato-eservice.interop.pagopa.it
session.tokens.duration.seconds=14400
interop-env=dev
max-polling-try-ms=50
max-polling-sleep-ms=1000
remote-wellknown-url=https://dev.interop.pagopa.it/.well-known/jwks.json
authorization.server.token.creation.url=https://auth.dev.interop.pagopa.it/token.oauth2
authorization.server.token-async.creation.url=https://auth.dev.interop.pagopa.it
client.assertion.jwt.audience=auth.dev.interop.pagopa.it/client-assertion

#ARCHIVIAZIONE DOCUMENTALE
s3.unsigned-document-base-path=interop-application-documents-dev-es1/qa/generated-documents/
s3.signed-document-base-path=interop-signed-application-documents-v2-dev-es1/qa/generated-documents/
s3.unsigned-event-base-path=interop-domain-events-dev-es1/year=:year/month=:onlyMonth/day=:onlyDay/
s3.signed-event-base-path=interop-signed-domain-events-v2-dev-es1/year=:year/month=:onlyMonth/day=:onlyDay/

#JWT-AUDIT
s3.unsigned-jwt-details-path=interop-generated-jwt-details-dev-es1/token-details/:year:onlyMonth:onlyDay/
s3.signed-jwt-details-path=interop-signed-jwt-audit-v2-dev-es1/token-details/:year:onlyMonth:onlyDay/
s3.unsigned-m2m-jwt-details-path=interop-generated-m2m-jwt-details-dev-es1/token-details/:year:onlyMonth:onlyDay/
s3.signed-m2m-jwt-details-path=interop-signed-m2m-jwt-audit-v2-dev-es1/token-details/:year:onlyMonth:onlyDay/
