#TRACING
pn.interop.tracing.base-url=https://api.dev.tracing.interop.pagopa.it
tracing.success.csv.filepath=src/main/resources/tracing/dev/tracing-ok.csv
tracing.error.csv.filepath=src/main/resources/tracing/dev/tracing-error.csv

bff.base-url=https://selfcare.dev.interop.pagopa.it/1.0/backend-for-frontend
interop-env=dev

