#TRACING
pn.interop.tracing.base-url=https://api.qa.tracing.interop.pagopa.it
tracing.success.csv.filepath=src/main/resources/tracing/qa/tracing-ok.csv
tracing.error.csv.filepath=src/main/resources/tracing/qa/tracing-error.csv

authorization.server.token.creation.url=https://auth.qa.interop.pagopa.it/token.oauth2
client.assertion.jwt.audience=auth.qa.interop.pagopa.it/client-assertion
bff.base-url=https://selfcare.qa.interop.pagopa.it/1.0/backend-for-frontend
interop-env=qa

#ARCHIVIAZIONE DOCUMENTALE
s3.unsigned-document-base-path=interop-application-documents-qa-es1
s3.signed-document-base-path=interop-signed-application-documents-qa-es1

#INTEROP GLOBAL PROPERTIES
remote-wellknown-url=https://qa.interop.pagopa.it/.well-known/jwks.json