#TRACING
pn.interop.tracing.base-url=https://api.dev.tracing.interop.pagopa.it
tracing.success.csv.filepath=src/main/resources/tracing/dev/tracing-ok.csv
tracing.error.csv.filepath=src/main/resources/tracing/dev/tracing-error.csv

#INTEROP GLOBAL PROPERTIES
bff.base-url=https://selfcare.dev.interop.pagopa.it/1.0/backend-for-frontend
m2m.base-url=https://api.dev.interop.pagopa.it/v2
session.tokens.duration.seconds=3600
interop-env=dev
max-polling-try-ms=50
max-polling-sleep-ms=1000
remote-wellknown-url=https://dev.interop.pagopa.it/.well-known/jwks.json