spring.profiles.active=qa
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN:%5p} ${PID:-} --- %X{scenarioId:-N/A} --- [%15.15thread] %-40.40logger{1} : %msg%n

#TRACING
pn.interop.tracing.bearerToken-1=${interop.configuration.tracing.bearerToken-1}
pn.interop.tracing.bearerToken-2=${interop.configuration.tracing.bearerToken-2}
tracing.csv.errors.path=src/main/resources/tracing/
tracing.csv.tmp.path=src/main/resources/tracing/tmp-files/

#INTEROP GLOBAL PROPERTIES
max-polling-try-ms=50
max-polling-sleep-ms=1000
default.delay=${default.workflow.delay:2500}

logging.level.it.pagopa.interop.maintenance.EnvDebugLogger=INFO
logging.level.it.pagopa.interop.maintenance.InteropMaintenanceServiceImpl=DEBUG