<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>it.pagopa.interop</groupId>
    <artifactId>interop-qa-tests</artifactId>
    <version>0.0.1-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <cucumber.version>7.8.1</cucumber.version>
        <aws.sdk.version>2.25.39</aws.sdk.version>
        <gson.version>2.11.0</gson.version>
        <spring.boot.version>2.5.12</spring.boot.version>
        <swagger.version>2.2.42</swagger.version>
        <findbugs.version>3.0.2</findbugs.version>
        <junit.platform.version>1.9.1</junit.platform.version>
        <lombok.version>1.18.30</lombok.version>
        <cucumber.reporting.version>5.10.2</cucumber.reporting.version>

        <!-- 14/04/2025: recentemente aggiornate le versioni dei framework di test. Si riportano di
         seguito quelle utilizzate in precedenza per facilitare eventuali rollback. -->
        <!-- <junit-jupiter.version>5.9.1</junit-jupiter.version> -->
        <!-- <junit.platform.version>1.9.1</junit.platform.version> -->
        <!-- <cucumber.version>7.8.1</cucumber.version> -->

        <junit-jupiter.version>5.12.1</junit-jupiter.version>
        <junit.platform.version>1.12.1</junit.platform.version>
        <cucumber.version>7.22.0</cucumber.version>
        <nimbus.version>9.37.3</nimbus.version>

        <org.mapstruct.version>1.6.3</org.mapstruct.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.fasterxml.jackson</groupId>
                <artifactId>jackson-bom</artifactId>
                <version>2.16.2</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <!-- Modulo common condiviso tra SEND e INTEROP -->
        <dependency>
            <groupId>it.pagopa.pn</groupId>
            <artifactId>common</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>

        <!-- BOUNCY CASTLE: gestione di file firmati digitalmente (p7m) -->
        <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcpkix-jdk15on</artifactId>
            <version>1.70</version>
        </dependency>
        <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcprov-jdk15on</artifactId>
            <version>1.70</version>
        </dependency>

        <!-- AWS SDK: Provides integration with Amazon Web Services, specifically for managing encryption keys using AWS Key Management Service (KMS) -->
        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>kms</artifactId>
            <version>${aws.sdk.version}</version>
        </dependency>

        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>cognitoidentityprovider</artifactId>
            <version>${aws.sdk.version}</version>
        </dependency>

        <!-- https://mvnrepository.com/artifact/com.amazonaws/aws-java-sdk-s3 -->
        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>s3</artifactId>
            <version>${aws.sdk.version}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.pdfbox</groupId>
            <artifactId>pdfbox</artifactId>
            <version>2.0.29</version>
        </dependency>

        <!-- https://mvnrepository.com/artifact/com.amazonaws/aws-java-sdk-dynamodb -->
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-java-sdk-dynamodb</artifactId>
            <version>1.12.792</version>
        </dependency>

        <!-- Gson: Library for serializing and deserializing Java objects to and from JSON format -->
        <dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
            <version>${gson.version}</version>
        </dependency>

        <!-- Apache Commons Compress -->
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-compress</artifactId>
            <version>1.24.0</version>
        </dependency>

        <dependency>
            <groupId>net.lingala.zip4j</groupId>
            <artifactId>zip4j</artifactId>
            <version>2.11.5</version>
        </dependency>

        <!-- Spring Boot -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <version>${spring.boot.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
            <version>${spring.boot.version}</version>
        </dependency>

        <!-- Swagger -->
        <dependency>
            <groupId>io.swagger.core.v3</groupId>
            <artifactId>swagger-annotations</artifactId>
            <version>${swagger.version}</version>
        </dependency>

        <!-- FindBugs Annotations -->
        <dependency>
            <groupId>com.google.code.findbugs</groupId>
            <artifactId>jsr305</artifactId>
            <version>${findbugs.version}</version>
        </dependency>

        <!-- Cucumber -->
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-java</artifactId>
            <version>${cucumber.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-spring</artifactId>
            <version>${cucumber.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-junit-platform-engine</artifactId>
            <version>${cucumber.version}</version>
            <scope>test</scope>
        </dependency>

        <!-- JUnit: Framework for unit testing in Java -->
        <dependency>
            <groupId>org.junit.platform</groupId>
            <artifactId>junit-platform-suite</artifactId>
            <scope>test</scope>
            <version>${junit.platform.version}</version>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
            <version>${junit-jupiter.version}</version>
        </dependency>

        <!-- Lombok -->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>${lombok.version}</version>
            <scope>provided</scope>
        </dependency>

        <!-- Cucumber Reporting: Provides support for generating reports from Cucumber tests -->
        <dependency>
            <groupId>net.masterthought</groupId>
            <artifactId>cucumber-reporting</artifactId>
            <version>${cucumber.reporting.version}</version>
            <scope>test</scope>

            <!-- Verrebbe qui usata una versione successiva di slf4j rispetto a quella usate da tutte
             le altre dep. del progetto, creando conflitti. Un'alternativa migliore sarebbe
             modernizzare tutto il progetto. -->
            <exclusions>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-api</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <!-- Apache Commons Lang -->
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>3.17.0</version>
        </dependency>

        <dependency>
            <groupId>com.opencsv</groupId>
            <artifactId>opencsv</artifactId>
            <version>5.9</version>
        </dependency>

        <!-- JWT -->
        <dependency>
            <groupId>io.jsonwebtoken</groupId>
            <artifactId>jjwt-api</artifactId>
            <version>0.12.6</version>
        </dependency>
        <dependency>
            <groupId>io.jsonwebtoken</groupId>
            <artifactId>jjwt-impl</artifactId>
            <version>0.12.6</version>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>io.jsonwebtoken</groupId>
            <artifactId>jjwt-jackson</artifactId> <!-- or jjwt-gson if Gson is preferred -->
            <version>0.12.6</version>
            <scope>runtime</scope>
        </dependency>

        <!-- Nimbus (per Dpop) -->
        <dependency>
            <groupId>com.nimbusds</groupId>
            <artifactId>nimbus-jose-jwt</artifactId>
            <version>${nimbus.version}</version>
        </dependency>

        <!-- Apache HttpClient (per Dpop e header duplicati) -->
        <dependency>
            <groupId>org.apache.httpcomponents.client5</groupId>
            <artifactId>httpclient5</artifactId>
            <version>5.2.1</version>
        </dependency>

        <dependency>
            <groupId>dev.turingcomplete</groupId>
            <artifactId>text-case-converter</artifactId>
            <version>2.0.0</version>
        </dependency>

        <!-- https://mvnrepository.com/artifact/org.springframework.retry/spring-retry -->
        <dependency>
            <groupId>org.springframework.retry</groupId>
            <artifactId>spring-retry</artifactId>
            <version>2.0.12</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/org.springframework/spring-aspects -->
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-aspects</artifactId>
            <version>7.0.0-M5</version>
        </dependency>

        <!-- Easy Random -->
        <dependency>
            <groupId>io.github.dvgaba</groupId>
            <artifactId>easy-random-core</artifactId>
            <version>7.1.1</version>
            <scope>test</scope>
        </dependency>

        <!-- MapStruct -->
        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct</artifactId>
            <version>${org.mapstruct.version}</version>
        </dependency>

        <!-- Necessario per il parsing di messaggi HTTP di tipo multipart -->
        <dependency>
            <groupId>commons-fileupload</groupId>
            <artifactId>commons-fileupload</artifactId>
            <version>1.5</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.2.5</version>
                <configuration>
                    <properties>
                        <configurationParameters>
                            cucumber.junit-platform.naming-strategy=long
                        </configurationParameters>
                    </properties>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <version>7.19.0</version>
                <executions>
                    <execution>
                        <id>generate-bff-client</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <phase>process-resources</phase>
                        <configuration>
                            <typeMappings>
                                <typeMapping>OffsetDateTime=java.lang.String</typeMapping>
                            </typeMappings>
                            <!-- <inputSpec>https://raw.githubusercontent.com/pagopa/interop-be-monorepo/refs/heads/develop/packages/api-clients/open-api/bffApi.yml</inputSpec> -->
                            <inputSpec>https://raw.githubusercontent.com/pagopa/interop-be-monorepo/refs/tags/2.21.0-RC1/packages/api-clients/open-api/bffApi.yml</inputSpec>
                            <generatorName>java</generatorName>
                            <library>resttemplate</library>
                            <generateApiTests>false</generateApiTests>
                            <generateModelTests>false</generateModelTests>
                            <skipValidateSpec>true</skipValidateSpec>
                            <configOptions>
                                <apiPackage>it.pagopa.interop.generated.openapi.clients.bff.api</apiPackage>
                                <modelPackage>it.pagopa.interop.generated.openapi.clients.bff.model</modelPackage>
                                <dateLibrary>java8</dateLibrary>
                                <annotationLibrary>none</annotationLibrary>
                                <documentationProvider>source</documentationProvider>
                                <openApiNullable>false</openApiNullable>
                                <useAbstractionForFiles>true</useAbstractionForFiles>
                                <useBeanValidation>false</useBeanValidation>
                                <additionalModelTypeAnnotations>
                                    @com.fasterxml.jackson.annotation.JsonInclude(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
                                </additionalModelTypeAnnotations>
                            </configOptions>
                            <apiPackage>it.pagopa.interop.generated.openapi.clients.bff.api</apiPackage>
                            <modelPackage>it.pagopa.interop.generated.openapi.clients.bff.model</modelPackage>
                        </configuration>
                    </execution>

                    <!-- authorizationServerApi -->
                    <execution>
                        <id>generate-authorization-server-api-client</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <phase>process-resources</phase>
                        <configuration>
                            <typeMappings>
                                <typeMapping>OffsetDateTime=java.lang.String</typeMapping>
                            </typeMappings>
                            <inputSpec>https://raw.githubusercontent.com/pagopa/interop-be-monorepo/refs/tags/2.21.0-RC1/packages/api-clients/open-api/authorizationServerApi.yml</inputSpec>
                            <generatorName>java</generatorName>
                            <library>resttemplate</library>
                            <generateApiTests>false</generateApiTests>
                            <generateModelTests>false</generateModelTests>
                            <skipValidateSpec>true</skipValidateSpec>
                            <configOptions>
                                <apiPackage>it.pagopa.interop.generated.openapi.clients.auth.api</apiPackage>
                                <modelPackage>it.pagopa.interop.generated.openapi.clients.auth.model</modelPackage>
                                <dateLibrary>java8</dateLibrary>
                                <annotationLibrary>none</annotationLibrary>
                                <documentationProvider>source</documentationProvider>
                                <openApiNullable>false</openApiNullable>
                                <useAbstractionForFiles>true</useAbstractionForFiles>
                                <useBeanValidation>false</useBeanValidation>
                                <additionalModelTypeAnnotations>
                                    @com.fasterxml.jackson.annotation.JsonInclude(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
                                </additionalModelTypeAnnotations>
                            </configOptions>
                            <apiPackage>it.pagopa.interop.generated.openapi.clients.auth.api</apiPackage>
                            <modelPackage>it.pagopa.interop.generated.openapi.clients.auth.model</modelPackage>
                        </configuration>
                    </execution>

                    <execution>
                        <id>generate-external-interop-tracing-client</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <phase>process-resources</phase>
                        <configuration>
                            <typeMappings>
                                <typeMapping>OffsetDateTime=java.lang.String</typeMapping>
                            </typeMappings>
                            <inputSpec>https://raw.githubusercontent.com/pagopa/interop-tracing-core/refs/tags/1.0.0-RC8/packages/api/open-api/api-external-interop-v1.yaml</inputSpec>
                            <generatorName>java</generatorName>
                            <library>resttemplate</library>
                            <generateApiTests>false</generateApiTests>
                            <generateModelTests>false</generateModelTests>
                            <skipValidateSpec>true</skipValidateSpec>
                            <configOptions>
                                <apiPackage>it.pagopa.interop.client.b2b.generated.openapi.clients.interop.tracing.api</apiPackage>
                                <modelPackage>it.pagopa.interop.client.b2b.generated.openapi.clients.interop.tracing.model</modelPackage>
                                <dateLibrary>java8</dateLibrary>
                                <annotationLibrary>none</annotationLibrary>
                                <documentationProvider>source</documentationProvider>
                                <openApiNullable>false</openApiNullable>
                                <useAbstractionForFiles>true</useAbstractionForFiles>
                                <useBeanValidation>false</useBeanValidation>
                                <additionalModelTypeAnnotations>
                                    @com.fasterxml.jackson.annotation.JsonInclude(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
                                </additionalModelTypeAnnotations>
                            </configOptions>
                            <apiPackage>it.pagopa.interop.client.b2b.generated.openapi.clients.interop.tracing.api</apiPackage>
                            <modelPackage>it.pagopa.interop.client.b2b.generated.openapi.clients.interop.tracing.model</modelPackage>
                        </configuration>
                    </execution>

                    <!-- Probing API -->
                    <execution>
                        <id>generate-probing-external-interop-client</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <phase>process-resources</phase>
                        <configuration>
                            <typeMappings>
                                <typeMapping>OffsetDateTime=java.lang.String</typeMapping>
                            </typeMappings>

                            <inputSpec>
                                https://raw.githubusercontent.com/pagopa/interop-probing-core/refs/heads/develop/packages/api-clients/open-api/probingApi.yaml
                            </inputSpec>

                            <generatorName>java</generatorName>
                            <library>resttemplate</library>

                            <generateApiTests>false</generateApiTests>
                            <generateModelTests>false</generateModelTests>

                            <configOptions>
                                <apiPackage>
                                    it.pagopa.interop.generated.openapi.clients.probing.api
                                </apiPackage>
                                <modelPackage>
                                    it.pagopa.interop.generated.openapi.clients.probing.model
                                </modelPackage>

                                <dateLibrary>java8</dateLibrary>
                                <annotationLibrary>none</annotationLibrary>
                                <documentationProvider>source</documentationProvider>
                                <openApiNullable>false</openApiNullable>
                                <useAbstractionForFiles>true</useAbstractionForFiles>
                                <useBeanValidation>false</useBeanValidation>

                                <additionalModelTypeAnnotations>
                                    @com.fasterxml.jackson.annotation.JsonInclude(
                                    com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL
                                    )
                                </additionalModelTypeAnnotations>
                            </configOptions>

                            <globalProperties>
                                <skipFormModel>false</skipFormModel>
                            </globalProperties>
                        </configuration>
                    </execution>

                    <!-- Probing Statistics API -->
                    <execution>
                        <id>generate-probing-statistics-interop-client</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <phase>process-resources</phase>
                        <configuration>
                            <typeMappings>
                                <typeMapping>OffsetDateTime=java.lang.String</typeMapping>
                            </typeMappings>

                            <inputSpec>
                                https://raw.githubusercontent.com/pagopa/interop-probing-core/refs/heads/develop/packages/api-clients/open-api/probingStatisticsApi.yaml
                            </inputSpec>

                            <generatorName>java</generatorName>
                            <library>resttemplate</library>

                            <generateApiTests>false</generateApiTests>
                            <generateModelTests>false</generateModelTests>

                            <configOptions>
                                <apiPackage>
                                    it.pagopa.interop.generated.openapi.clients.probingStatistics.api
                                </apiPackage>
                                <modelPackage>
                                    it.pagopa.interop.generated.openapi.clients.probingStatistics.model
                                </modelPackage>

                                <dateLibrary>java8</dateLibrary>
                                <annotationLibrary>none</annotationLibrary>
                                <documentationProvider>source</documentationProvider>
                                <openApiNullable>false</openApiNullable>
                                <useAbstractionForFiles>true</useAbstractionForFiles>
                                <useBeanValidation>false</useBeanValidation>

                                <additionalModelTypeAnnotations>
                                    @com.fasterxml.jackson.annotation.JsonInclude(
                                    com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL
                                    )
                                </additionalModelTypeAnnotations>
                            </configOptions>

                            <globalProperties>
                                <skipFormModel>false</skipFormModel>
                            </globalProperties>
                        </configuration>
                    </execution>

                    <execution>
                        <id>generate-m2mGateway-client</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <phase>process-resources</phase>
                        <configuration>
                            <typeMappings>
                                <typeMapping>OffsetDateTime=java.lang.String</typeMapping>
                            </typeMappings>
                            <inputSpec>https://raw.githubusercontent.com/pagopa/interop-be-monorepo/refs/tags/2.21.0-RC1/packages/api-clients/open-api/m2mGatewayApi.yml</inputSpec>
                            <generatorName>java</generatorName>
                            <library>resttemplate</library>
                            <generateApiTests>false</generateApiTests>
                            <generateModelTests>false</generateModelTests>
                            <configOptions>
                                <apiPackage>it.pagopa.interop.generated.openapi.clients.m2mGateway.api</apiPackage>
                                <modelPackage>it.pagopa.interop.generated.openapi.clients.m2mGateway.model</modelPackage>
                                <dateLibrary>java8</dateLibrary>
                                <annotationLibrary>none</annotationLibrary>
                                <documentationProvider>source</documentationProvider>
                                <openApiNullable>false</openApiNullable>
                                <useAbstractionForFiles>true</useAbstractionForFiles>
                                <useBeanValidation>false</useBeanValidation>
                                <additionalModelTypeAnnotations>
                                    @com.fasterxml.jackson.annotation.JsonInclude(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
                                </additionalModelTypeAnnotations>
                            </configOptions>
                            <apiPackage>it.pagopa.interop.generated.openapi.clients.m2mGateway.api</apiPackage>
                            <modelPackage>it.pagopa.interop.generated.openapi.clients.m2mGateway.model</modelPackage>
                            <globalProperties>
                                <skipFormModel>false</skipFormModel>
                            </globalProperties>
                        </configuration>
                    </execution>

                    <execution>
                        <id>generate-m2mGateway-v3-client</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <phase>process-resources</phase>
                        <configuration>
                            <typeMappings>
                                <typeMapping>OffsetDateTime=java.lang.String</typeMapping>
                            </typeMappings>
                            <!--<inputSpec>https://raw.githubusercontent.com/pagopa/interop-be-monorepo/refs/heads/release/2.10.0/packages/api-clients/open-api/m2mGatewayApi.yml</inputSpec> -->
                            <inputSpec>https://raw.githubusercontent.com/pagopa/interop-be-monorepo/refs/tags/2.21.0-RC1/packages/api-clients/open-api/m2mGatewayApiV3.yml</inputSpec>
                            <generatorName>java</generatorName>
                            <library>resttemplate</library>
                            <generateApiTests>false</generateApiTests>
                            <generateModelTests>false</generateModelTests>
                            <configOptions>
                                <apiPackage>it.pagopa.interop.generated.openapi.clients.m2mGatewayV3.api</apiPackage>
                                <modelPackage>it.pagopa.interop.generated.openapi.clients.m2mGatewayV3.model</modelPackage>
                                <dateLibrary>java8</dateLibrary>
                                <annotationLibrary>none</annotationLibrary>
                                <documentationProvider>source</documentationProvider>
                                <openApiNullable>false</openApiNullable>
                                <useAbstractionForFiles>true</useAbstractionForFiles>
                                <useBeanValidation>false</useBeanValidation>
                                <additionalModelTypeAnnotations>
                                    @com.fasterxml.jackson.annotation.JsonInclude(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
                                </additionalModelTypeAnnotations>
                            </configOptions>
                            <apiPackage>it.pagopa.interop.generated.openapi.clients.m2mGatewayV3.api</apiPackage>
                            <modelPackage>it.pagopa.interop.generated.openapi.clients.m2mGatewayV3.model</modelPackage>
                            <globalProperties>
                                <skipFormModel>false</skipFormModel>
                            </globalProperties>
                        </configuration>
                    </execution>

                    <execution>
                        <id>generate-tenant-process-client</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <phase>process-resources</phase>
                        <configuration>
                            <typeMappings>
                                <typeMapping>OffsetDateTime=java.lang.String</typeMapping>
                            </typeMappings>
                            <!-- <inputSpec>https://raw.githubusercontent.com/pagopa/interop-be-monorepo/refs/heads/develop/packages/api-clients/open-api/bffApi.yml</inputSpec> -->
                            <inputSpec>https://raw.githubusercontent.com/pagopa/interop-be-monorepo/refs/tags/2.21.0-RC1/packages/api-clients/open-api/tenantApi.yml</inputSpec>
                            <generatorName>java</generatorName>
                            <library>resttemplate</library>
                            <generateApiTests>false</generateApiTests>
                            <generateModelTests>false</generateModelTests>
                            <skipValidateSpec>true</skipValidateSpec>
                            <configOptions>
                                <apiPackage>it.pagopa.interop.generated.openapi.clients.tenant-process.api</apiPackage>
                                <modelPackage>it.pagopa.interop.generated.openapi.clients.tenant-process.model</modelPackage>
                                <dateLibrary>java8</dateLibrary>
                                <annotationLibrary>none</annotationLibrary>
                                <documentationProvider>source</documentationProvider>
                                <openApiNullable>false</openApiNullable>
                                <useAbstractionForFiles>true</useAbstractionForFiles>
                                <useBeanValidation>false</useBeanValidation>
                                <additionalModelTypeAnnotations>
                                    @com.fasterxml.jackson.annotation.JsonInclude(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
                                </additionalModelTypeAnnotations>
                            </configOptions>
                            <apiPackage>it.pagopa.interop.generated.openapi.clients.tenant-process.api</apiPackage>
                            <modelPackage>it.pagopa.interop.generated.openapi.clients.tenant-process.model</modelPackage>
                        </configuration>
                    </execution>

                </executions>
            </plugin>

            <!-- TODO: le patch al codice generato sono necessarie per far sì che i modelli LinkableEService e LinkableEServiceTemplate estendano LinkableResource, in modo da poter essere trattati in maniera polimorfica. Altri file sono modificati per avere coerenza con ResourceKindEnum. In futuro, quando sarà possibile aggiornare la versione di openapi-generator, è auspicabile che queste patch non siano più necessarie. -->
            <plugin>
                <groupId>com.google.code.maven-replacer-plugin</groupId>
                <artifactId>replacer</artifactId>
                <version>1.5.3</version>
                <executions>

                    <execution>
                        <id>patch-linkable-eservice</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>replace</goal>
                        </goals>
                        <configuration>
                            <file>${project.build.directory}/generated-sources/openapi/src/main/java/it/pagopa/interop/generated/openapi/clients/bff/model/LinkableEService.java</file>
                            <regex>true</regex>
                            <replacements>
                                <replacement>
                                    <token>public class LinkableEService \{</token>
                                    <value>public class LinkableEService extends LinkableResource {</value>
                                </replacement>
                                <replacement>
                                    <token>/\*\*\s*\*\s*Get resourceKind[\s\S]*?public\s+ResourceKindEnum\s+getResourceKind\(\)\s*\{[\s\S]*?\}</token>
                                    <value></value>
                                </replacement>
                            </replacements>
                        </configuration>
                    </execution>

                    <execution>
                        <id>patch-linkable-eservice-template</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>replace</goal>
                        </goals>
                        <configuration>
                            <file>${project.build.directory}/generated-sources/openapi/src/main/java/it/pagopa/interop/generated/openapi/clients/bff/model/LinkableEServiceTemplate.java</file>
                            <regex>true</regex>
                            <replacements>
                                <replacement>
                                    <token>public class LinkableEServiceTemplate \{</token>
                                    <value>public class LinkableEServiceTemplate extends LinkableResource {</value>
                                </replacement>
                                <replacement>
                                    <token>/\*\*\s*\*\s*Get resourceKind[\s\S]*?public\s+ResourceKindEnum\s+getResourceKind\(\)\s*\{[\s\S]*?\}</token>
                                    <value></value>
                                </replacement>
                            </replacements>
                        </configuration>
                    </execution>

                    <execution>
                        <id>patch-linked-resource</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>replace</goal>
                        </goals>
                        <configuration>
                            <file>${project.build.directory}/generated-sources/openapi/src/main/java/it/pagopa/interop/generated/openapi/clients/bff/model/LinkedResource.java</file>
                            <regex>true</regex>
                            <replacements>
                                <replacement>
                                    <token>@JsonIgnoreProperties\([\s\S]*?value\s*=\s*"resourceKind"[\s\S]*?\)\s*\n?</token>
                                    <value></value>
                                </replacement>
                                <replacement>
                                    <token>JsonTypeInfo\.Id\.NAME</token>
                                    <value>JsonTypeInfo.Id.NONE</value>
                                </replacement>
                                <replacement>
                                    <token>ESERVICE_TEMPLATE\(String\.valueOf\("ESERVICE_TEMPLATE"\)\);</token>
                                    <value><![CDATA[ESERVICE_TEMPLATE(String.valueOf("ESERVICE_TEMPLATE")),
    ESERVICE(String.valueOf("ESERVICE"));]]></value>
                                </replacement>
                                <replacement>
                                    <token>@JsonInclude\(value = JsonInclude.Include.ALWAYS\)[\s\n\r]+public UUID getEservice</token>
                                    <value>@JsonInclude(value = JsonInclude.Include.NON_NULL)
                                        public UUID getEservice</value>
                                </replacement>
                                <replacement>
                                    <token>@JsonInclude\(value = JsonInclude.Include.ALWAYS\)[\s\n\r]+public void setEservice</token>
                                    <value>@JsonInclude(value = JsonInclude.Include.NON_NULL)
                                        public void setEservice</value>
                                </replacement>
                            </replacements>
                        </configuration>
                    </execution>

                    <execution>
                        <id>patch-linkable-resource</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>replace</goal>
                        </goals>
                        <configuration>
                            <file>${project.build.directory}/generated-sources/openapi/src/main/java/it/pagopa/interop/generated/openapi/clients/bff/model/LinkableResource.java</file>
                            <regex>true</regex>
                            <replacements>
                                <replacement>
                                    <token>ESERVICE_TEMPLATE\(String\.valueOf\("ESERVICE_TEMPLATE"\)\);</token>
                                    <value><![CDATA[ESERVICE_TEMPLATE(String.valueOf("ESERVICE_TEMPLATE")),
    ESERVICE(String.valueOf("ESERVICE"));]]></value>
                                </replacement>
                            </replacements>
                        </configuration>
                    </execution>

                    <execution>
                        <id>patch-linkable-resource-request</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>replace</goal>
                        </goals>
                        <configuration>
                            <file>${project.build.directory}/generated-sources/openapi/src/main/java/it/pagopa/interop/generated/openapi/clients/bff/model/LinkableResourceRequest.java</file>
                            <regex>true</regex>
                            <replacements>
                                <replacement>
                                    <token>@JsonIgnoreProperties\([\s\S]*?value\s*=\s*"resourceKind"[\s\S]*?\)\s*\n?</token>
                                    <value></value>
                                </replacement>
                                <replacement>
                                    <token>JsonTypeInfo\.Id\.NAME</token>
                                    <value>JsonTypeInfo.Id.NONE</value>
                                </replacement>
                                <replacement>
                                    <token>ESERVICE_TEMPLATE\(String\.valueOf\("ESERVICE_TEMPLATE"\)\);</token>
                                    <value><![CDATA[ESERVICE_TEMPLATE(String.valueOf("ESERVICE_TEMPLATE")),
    ESERVICE(String.valueOf("ESERVICE"));]]></value>
                                </replacement>
                                <replacement>
                                    <token>@JsonInclude\(value = JsonInclude.Include.ALWAYS\)[\s\n\r]+public UUID getEservice</token>
                                    <value>@JsonInclude(value = JsonInclude.Include.NON_NULL)
                                        public UUID getEservice</value>
                                </replacement>
                                <replacement>
                                    <token>@JsonInclude\(value = JsonInclude.Include.ALWAYS\)[\s\n\r]+public void setEservice</token>
                                    <value>@JsonInclude(value = JsonInclude.Include.NON_NULL)
                                        public void setEservice</value>
                                </replacement>
                            </replacements>
                        </configuration>
                    </execution>

                    <!-- TODO: le patch al codice generato sono necessarie per far sì che il modello StandardCertifiedTenantAttribute estenda CertifiedTenantAttribute, in modo da poter essere trattati in maniera polimorfica.-->

                    <execution>
                        <id>patch-StandardCertifiedTenantAttribute</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>replace</goal>
                        </goals>
                        <configuration>
                            <file>
                                ${project.build.directory}/generated-sources/openapi/src/main/java/it/pagopa/interop/generated/openapi/clients/bff/model/StandardCertifiedTenantAttribute.java
                            </file>
                            <regex>true</regex>
                            <replacements>
                                <replacement>
                                    <token>public class StandardCertifiedTenantAttribute \{</token>
                                    <value>public class StandardCertifiedTenantAttribute extends CertifiedTenantAttribute {
                                    </value>
                                </replacement>
                                <replacement>
                                    <token>/\*\*\s*\*\s*Get kind[\s\S]*?public\s+KindEnum\s+getKind\(\)\s*\{[\s\S]*?\}\s*\n?</token>
                                    <value></value>
                                </replacement>

                                <replacement>
                                    <token>\s*public static final String JSON_PROPERTY_KIND = "kind";\s*@javax.annotation.Nonnull\s*private KindEnum kind;</token>
                                    <value></value>
                                </replacement>

                                <replacement>
                                    <token>public\s+enum\s+KindEnum\s*\{[\s\S]*?(?=public\s+static\s+final\s+String\s+JSON_PROPERTY_ID\s*=\s*"id";)</token>
                                    <value></value>
                                </replacement>
                            </replacements>
                        </configuration>
                    </execution>

                    <execution>
                        <id>patch-certified-discrete-tenant-attribute</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>replace</goal>
                        </goals>
                        <configuration>
                            <file>${project.build.directory}/generated-sources/openapi/src/main/java/it/pagopa/interop/generated/openapi/clients/bff/model/CertifiedDiscreteTenantAttribute.java</file>
                            <regex>true</regex>
                            <replacements>
                                <replacement>
                                    <token>public class CertifiedDiscreteTenantAttribute \{</token>
                                    <value>public class CertifiedDiscreteTenantAttribute extends CertifiedTenantAttribute {</value>
                                </replacement>

                                <replacement>
                                    <token>/\*\*\s*\*\s*Get kind[\s\S]*?public\s+KindEnum\s+getKind\(\)\s*\{[\s\S]*?\}\s*\n?</token>
                                    <value></value>
                                </replacement>

                                <replacement>
                                    <token>\s*public static final String JSON_PROPERTY_KIND = "kind";\s*@javax.annotation.Nonnull\s*private KindEnum kind;</token>
                                    <value></value>
                                </replacement>

                                <replacement>
                                    <token>public\s+enum\s+KindEnum\s*\{[\s\S]*?(?=public\s+static\s+final\s+String\s+JSON_PROPERTY_ID\s*=\s*"id";)</token>
                                    <value></value>
                                </replacement>
                            </replacements>
                        </configuration>
                    </execution>

                    <execution>
                        <id>patch-tenant-attribute</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>replace</goal>
                        </goals>
                        <configuration>
                            <file>${project.build.directory}/generated-sources/openapi/src/main/java/it/pagopa/interop/generated/openapi/clients/bff/model/CertifiedTenantAttribute.java</file>
                            <regex>true</regex>
                            <replacements>
                                <replacement>
                                    <token>CERTIFIED_DISCRETE\(String\.valueOf\("CERTIFIED_DISCRETE"\)\);</token>
                                    <value><![CDATA[CERTIFIED_DISCRETE(String.valueOf("CERTIFIED_DISCRETE")),
    CERTIFIED(String.valueOf("CERTIFIED"));]]></value>
                                </replacement>
                                <replacement>
                                    <token>private KindEnum kind;</token>
                                    <value>protected KindEnum kind;</value>
                                </replacement>
                            </replacements>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <source>17</source>
                    <target>17</target>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.mapstruct</groupId>
                            <artifactId>mapstruct-processor</artifactId>
                            <version>${org.mapstruct.version}</version>
                        </path>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>${lombok.version}</version>
                        </path>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok-mapstruct-binding</artifactId>
                            <version>0.2.0</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
