package it.pagopa.pn.interop.cucumber.steps.archiviazione_documentale.enums;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum InteropFile {
    AGREEMENT_CONTRACT_DOC,
    RISK_ANALYSIS_DOC,
    CONSUMER_DELEGATION_REVOKED_DOC,
    CONSUMER_DELEGATION_REQUEST_DOC,
    PRODUCER_DELEGATION_REVOKED_DOC,
    PRODUCER_DELEGATION_REQUEST_DOC,

    KEY_ADDED_EVENTS_LOG,
    KEY_DELETED_EVENTS_LOG,
    CLIENT_DELETED_EVENTS_LOG,
    AGREEMENT_ACTIVATE_EVENTS_LOG,
    AGREEMENT_SUSPENDED_BY_CONSUMER_EVENTS_LOG,
    AGREEMENT_ARCHIVED_BY_CONSUMER_EVENTS_LOG,
    PURPOSE_ACTIVATE_EVENTS_LOG,
    NEW_PURPOSE_VERSION_ACTIVATE_EVENTS_LOG,
    ESERVICE_DESCRIPTOR_EVENTS_LOG,
    CONSUMER_DELEGATION_REVOKED_EVENTS_LOG,
    CONSUMER_DELEGATION_REQUEST_EVENTS_LOG,
    PRODUCER_DELEGATION_REVOKED_EVENTS_LOG,

    AUDIT_JWT_EVENTS_LOG;
}
