# UAT ENV
pn.tax-id.mario-cucumber=FRMTTR76M06B715E
pn.tax-id.mario-gherkin=CLMCST42R12D969Z
pn.tax-id.cucumber-srl=20517490320
pn.tax-id.cucumber-spa=20517490320
pn.tax-id.gherkin-srl=12666810299
pn.tax-id.gherkin-spa=12666810299
pn.tax-id.cucumber-analogic=LBPHLS94A56C826R
pn.tax-id.gherkin-analogic=80048790176
pn.tax-id.cucumber-society=20517490320
pn.tax-id.gherkin-irreperibile=02455090981
pn.tax-id.leonardo-da-vinci=DVNLRD52D15M059P
pn.tax-id.galileo-galilei=GLLGLL64B15G702I
pn.tax-id.comune-1=01199250158
pn.tax-id.comune-2=00215150236
pn.tax-id.comune-multi=80016350821
pn.tax-id.comune-son=03509990788
pn.tax-id.comune-root=03509990788
#ERRORE D01
pn.tax-id.user-indirizzo-non-valido-d01=CLMCST42R12D969Z
#INDIRIZZO VALIDO CENSITO IN ANPR
pn.tax-id.user-indirizzo-valido-anpr=DVNLRD52D15M059P

