# UAT ENV
pn.recipient.mario-cucumber.tax-id=FRMTTR76M06B715E
# ---------------------------------
pn.recipient.mario-gherkin.tax-id=CLMCST42R12D969Z
pn.recipient.mario-gherkin.uid=a6c1350d-1d69-4209-8bf8-31de58c79d6e
# ---------------------------------
pn.recipient.cucumber-srl.tax-id=20517490320
# ---------------------------------
pn.recipient.cucumber-spa.tax-id=20517490320
pn.recipient.cucumber-spa.uid=b05de777-80c6-4549-a054-d8dfda139c62
# ---------------------------------
pn.recipient.gherkin-srl.tax-id=12666810299
# ---------------------------------
pn.recipient.gherkin-spa.tax-id=12666810299
# ---------------------------------
pn.recipient.cucumber-analogic.tax-id=LBPHLS94A56C826R
# ---------------------------------
pn.recipient.gherkin-analogic.tax-id=80048790176
# ---------------------------------
pn.recipient.cucumber-society.tax-id=20517490320
# ---------------------------------
pn.recipient.gherkin-irreperibile.tax-id=02455090981
# ---------------------------------
pn.recipient.leonardo-da-vinci.tax-id=DVNLRD52D15M059P
# ---------------------------------
pn.recipient.galileo-galilei.tax-id=GLLGLL64B15G702I
pn.recipient.galileo-galilei.uid=82e80ed2-d93b-4e85-9767-cc6ae150fb80
# ---------------------------------
pn.recipient.alda-merini.tax-id=12666810299
pn.recipient.alda-merini.uid=8f409ca6-fc3d-46c3-8da7-69cd9a1e9e62
# ---------------------------------
pn.recipient.dino-sauro.tax-id=DSRDNI00A01A225I
pn.recipient.dino-sauro.uid=c270c377-6c54-4cbc-80c0-f2cfbcf35b0b
# ---------------------------------
pn.recipient.comune-1.tax-id=01199250158
# ---------------------------------
pn.recipient.comune-2.tax-id=00215150236
# ---------------------------------
pn.recipient.comune-multi.tax-id=80016350821
# ---------------------------------
pn.recipient.comune-son.tax-id=03509990788
# ---------------------------------
pn.recipient.comune-root.tax-id=03509990788
#ERRORE D01
pn.recipient.user-indirizzo-non-valido-d01.tax-id=CLMCST42R12D969Z
#INDIRIZZO VALIDO CENSITO IN ANPR
pn.recipient.user-indirizzo-valido-anpr.tax-id=DVNLRD52D15M059P
