openapi: "3.0.0"
info:
  version: 1.0.0
  title: Test API with Missing Servers
paths:
  /resource:
    get:
      description: Returns a resource
      operationId: getResource
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
components:
  schemas:
    Resource:
      type: object

