upload.files.pdf=upload-test-files/documento-test-qa.pdf
upload.files.json=upload-test-files/sample-permesso.json
upload.files.md=upload-test-files/sample-permesso.md
upload.files.xsd=upload-test-files/sample-permesso.xsd
upload.files.yml=upload-test-files/sample-permesso.yml
upload.files.yaml=upload-test-files/sample-permesso.yaml
upload.files.txt=upload-test-files/sample-permesso.txt
upload.files.wsdl=upload-test-files/sample-permesso.wsdl
upload.files.png=upload-test-files/sample-non-permesso.png
upload.files.html=upload-test-files/sample-non-permesso.html
upload.files.docx=upload-test-files/sample-non-permesso.docx
upload.files.zip=upload-test-files/sample-non-permesso.zip
upload.files.msi=upload-test-files/7z2602-x64.msi
upload.files.exe=upload-test-files/7z2602-x64.exe
upload.files.sh=upload-test-files/sample-non-permesso.sh
upload.files.bat=upload-test-files/sample-non-permesso.bat
upload.files.cmd=upload-test-files/sample-non-permesso.cmd
upload.files.js=upload-test-files/sample-non-permesso.js
upload.files.bash=upload-test-files/sample-non-permesso.bash
upload.files.ps1=upload-test-files/sample-non-permesso.ps1
upload.files.interface=interface.yaml

