rdb:
  base-url:  https://api-io.dev.cstar.pagopa.it/idpay-itn/register

role:
  productor-1:
    uid: "99457865-8a65-467f-aeec-7ce9f71c361a"
    name: Giuseppe
    familyName: Polignano
    orgId: b5ae0b41-b854-414e-8295-078595ee1db4
    orgRole: operatore
    orgFc: "00005005050"

  productor-2:
    uid: 195da70f-d3f0-4c57-b62e-ef471348e920
    name: Lorenzo
    familyName: Lollo
    orgId: b5ae0b41-b854-414e-8295-078595ee1db5
    orgRole: operatore
    orgFc: "00005005051"

  invitalia:
    uid: 195da70f-d3f0-4c57-b62e-ef471348e920
    name: Lorenzo
    familyName: Lollo
    orgId: b5ae0b41-b854-414e-8295-078595ee1da1
    orgRole: invitalia
    orgFc: "00005005052"

removeTos.endpoint: https://idpay.itn.internal.dev.cstar.pagopa.it/idpayassetregisterbackend/idpay/consent