rdb:
  base-url: https://api-io.uat.cstar.pagopa.it/idpay-itn/register

merchant:
  base-url: https://api-io.uat.cstar.pagopa.it/idpay-itn/merchant

role:
  productor-1:
    uid: "e88fe25f-ccfa-4962-8f62-f1450fd78ad0"
    name: Gianantonio
    familyName: Grassi
    orgId: 8bd31e63-a8e8-4cbc-b06d-bc69f32c3fde
    orgVat: "13123784130"
    orgFc: "13123784130"
    orgName: Produttore di Elettrodomestici 04Luglio
    orgPartyRole: OPERATOR
    orgRole: operatore

  productor-2:
    uid: "47090ab7-3bf7-411d-b200-9bbf1451435d"
    name: carlo
    familyName: carlo
    orgId: 999e1892-08e8-4d13-bec9-54814cd31b0c
    orgVat: "13123784123"
    orgFc: "13123784123"
    orgName: Produttore Matrix
    orgPartyRole: OPERATOR
    orgRole: operatore

  invitalia-l1:
    uid: "47090ab7-3bf7-411d-b200-9bbf1451435d"
    name: carlo
    familyName: carlo
    orgId: 918692a6-dc2e-4f61-a36b-a8f003202f86
    orgVat: "05678721001"
    orgFc: "05678721001"
    orgName: Ag.Naz.Attrazione Investimenti Sviluppo Impresa Spa
    orgPartyRole: Operatore Invitalia
    orgRole: invitalia

  invitalia-l2:
    uid: "2b10852f-a4fd-4ae8-9dfc-ac3578fc5b21"
    name: Marie
    familyName: Curie
    orgId: 918692a6-dc2e-4f61-a36b-a8f003202f86
    orgVat: "05678721001"
    orgFc: "05678721001"
    orgName: Ag.Naz.Attrazione Investimenti Sviluppo Impresa Spa
    orgPartyRole: Admin Invitalia
    orgRole: invitalia_admin

  merchant-root:
    uid: "330f7958-e839-494c-a114-64fea26b8e85"
    name: esercente
    familyName: test
    email: esercenteTest@test.email.it
    acquirerId: PAGOPA
    merchantId: 3a602b17-ac1c-3029-9e78-0a4bbb8693d4
    orgId: f06ce6ee-9605-4327-89a6-0fb9f22b3a06
    orgVat: "33444433488"
    orgName: Esercente di test IdPay
    orgPartyRole: MANAGER
    orgRole: admin

removeTos.endpoint: https://idpay.itn.internal.uat.cstar.pagopa.it/idpayassetregisterbackend/idpay/consent