name: QA workflow

on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        required: true
        type: environment
      testSuite:
        description: 'Choose the test suite to run'
        required: false
        default: NrtTest
        type: string

defaults:
    run:
      shell: bash
      
permissions:
  id-token: write
  contents: read

jobs:
  inputs:
    runs-on: ubuntu-22.04
    environment: ${{ inputs.environment }}

    steps:
      - name: Print Inputs
        id: print_inputs
        run: |
          echo "- environment: \`${{ inputs.environment }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- branch name: \`${{ github.ref_name }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- testSuite: \`${{ inputs.testSuite }}\`" >> $GITHUB_STEP_SUMMARY

  create_runner:
    name: Create Self-Hosted Runner
    runs-on: ubuntu-22.04
    environment: ${{ inputs.environment }}

    steps:
      - name: Start GitHub Runner
        id: start_runner
        uses: pagopa/interop-github-runner-aws-create-action@main
        with:
            environment: ${{ inputs.environment }}
            aws_region: ${{ secrets.AWS_REGION }}
            iam_role_arn: ${{ secrets.ECS_IAM_ROLE_ARN }}
            ecs_cluster_name: ${{ secrets.ECS_CLUSTER_NAME }}
            ecs_task_definition: ${{ secrets.ECS_TASK_DEFINITION }}
            ecs_container_name: ${{ vars.ECS_TASK_CONTAINER_NAME }}
            ecs_task_max_duration_seconds: ${{ vars.ECS_TASK_MAX_DURATION_SECONDS }}
            ecs_task_subnet_id: ${{ secrets.SUBNET_ID }}
            ecs_task_sec_group: ${{ secrets.SEC_GROUP_ID }}
            pat_token: ${{ secrets.BOT_TOKEN }}

  run_test:
    name: Run Cucumber Test Suite
    needs: create_runner
    runs-on: [self-hosted, "run_id:${{ inputs.environment }}-${{ github.run_id }}"]
    environment: ${{ inputs.environment }}
    env: 
      ENVIRONMENT: qa
      ST_VERBOSE_MODE: ${{ vars.ST_VERBOSE_MODE }}

    steps:
      - name: Clone QA test repo
        id: clone_qa_repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref_name }} # Branch name to clone
          fetch-depth: 1  # Clone only the last commit

      - name: Run QA tests
        id: run_qa_tests
        shell: bash
        run: |
          echo "Run test"
          ( cd ./pn-b2b-client/interop-qa-tests && ./mvnw -Dtest=it.pagopa.pn.interop.cucumber.${{ inputs.testSuite }} clean verify )

  delete_runner:
    name: Delete Self-Hosted Runner
    needs: run_test
    if: ${{ always() }}
    runs-on: ubuntu-22.04
    environment: ${{ inputs.environment }}

    steps:
      - name: Stop Github Runner
        id: stop_runner
        uses: pagopa/interop-github-runner-aws-cleanup-action@main
        with:
            environment: ${{ inputs.environment }}
            aws_region: ${{ secrets.AWS_REGION }}
            iam_role_arn: ${{ secrets.ECS_IAM_ROLE_ARN }}
            ecs_cluster_name: ${{ secrets.ECS_CLUSTER_NAME }}
            pat_token: ${{ secrets.BOT_TOKEN }}
